### ISSUE TITLE
Website bahut badiya hai.

### ISSUE THREAD

**Issue by sj-on** [RK-Duke/Tindog-Demo-Website#1]
[Ye aapne khud banayee?](https://rk-duke.github.io/Tindog-Demo-Website/)

**Comment by RK-Duke** [comment]
Learning project tha vase.. but khud hu banaya hai

**Comment by rudrakumar2012** [comment]
> [Ye aapne khud banayee?](https://rk-duke.github.io/Tindog-Demo-Website/)

Learning project tha concept clear karne ke liye CSS n HTML with Bootstrap ... So haan Khud hi banaya hai

**Comment by sj-on** [comment]
> > [Ye aapne khud banayee?](https://rk-duke.github.io/Tindog-Demo-Website/)
> 
> Learning project tha concept clear karne ke liye CSS n HTML with Bootstrap ... So haan Khud hi banaya hai

Badiyya hai.

**Comment by rudrakumar2012** [comment]
> > > [Ye aapne khud banayee?](https://rk-duke.github.io/Tindog-Demo-Website/)
> > 
> > 
> > Learning project tha concept clear karne ke liye CSS n HTML with Bootstrap ... So haan Khud hi banaya hai
> 
> Badiyya hai.

Thank you very much.
